# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: 📬 Request System Access
    url: https://your.helpdesk.link
    about: Request access or login credentials for hospital systems.
